name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04  # Se especifica la versión de Ubuntu para evitar la advertencia

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install  # Instalar las dependencias de npm

    - name: Build the project
      run: npm run build  # Construir el proyecto con Parcel

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist  # Directorio donde Parcel genera los archivos

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Subir a la rama gh-pages
          folder: ./dist  # Carpeta de salida de Parcel
